# Generated by Django 4.2.8 on 2024-05-07 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_shippinginformation_adress2_ordermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
