# Generated by Django 4.2.8 on 2024-05-08 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_ordermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingInformation',
        ),
    ]
