# Generated by Django 4.2.8 on 2025-02-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_alter_productmodel_image'),
        ('users', '0005_delete_shippinginformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='product',
            field=models.ManyToManyField(to='seller.productmodel'),
        ),
    ]
