# Generated by Django 4.2.8 on 2024-03-27 23:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='product_img', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tag', models.ManyToManyField(to='seller.tagmodel')),
            ],
        ),
    ]
