# Generated by Django 4.2.8 on 2024-04-29 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_img', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
