# Generated by Django 4.2.8 on 2024-06-19 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_productmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(default='PRODUCT.png', upload_to='product_img', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
