# Generated by Django 4.2.8 on 2024-05-07 00:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(max_length=1000)),
                ('price', models.IntegerField(max_length=100000)),
                ('image', models.ImageField(upload_to='product_img', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])])),
            ],
        ),
    ]
