# Generated by Django 4.2.8 on 2025-02-17 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
